---
- hosts: production
  become: true
  vars:
    username: ansible
    password: $6$rlLdG6wd1CT8v7i$7psP8l26lmaPhT3cigoYYXhjG28CtD1ifILq9KzvA0W0TH2Hj4.iO43RkPWgJGIi60Mz0CsxWbRVBSQkAY95W0
    public_key: ~/.ssh/id_ed25519.pub
  roles:
    - common
    #  - ufw
    - user
  #  - nginx
  #  - php
  #  - mysql
  #  - wp-cli
  #  - ssh
